env: "local" # local, dev, prod
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
max_files_per_task: 3
max_concurrent_tasks: 3
allowed_extensions:
  - ".pdf"
  - ".jpeg"
temp_dir: "./temp_dir/"